BlogRazor.Web/Pages/Admin/Blogs/Add.cshtml.cs
using BlogRazor.Web.Data;
using BlogRazor.Web.Models.Domain;
using BlogRazor.Web.Models.ViewModels;
using BlogRazor.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;

namespace BlogRazor.Web.Pages.Admin.Blogs
{
    [Authorize(Roles = "Admin")]
    public class AddModel : PageModel
    {

        private readonly IBlogPostRepository blogPostRepository;

        [BindProperty]
        public AddBlogPost AddBlogPostRequest { get; set; }

        public AddModel(IBlogPostRepository blogPostRepository)
        {
            this.blogPostRepository = blogPostRepository;
        }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPost()
        {

            if (ModelState.IsValid)
            {
                var blogPost = new BlogPost()
                {
                    Heading = AddBlogPostRequest.Heading,
                    PageTitle = AddBlogPostRequest.PageTitle,
                    Content = AddBlogPostRequest.Content,
                    ShortDescription = AddBlogPostRequest.ShortDescription,
                    PublishedDate = AddBlogPostRequest.PublishedDate,
                    Author = AddBlogPostRequest.Author,
                    Visible = AddBlogPostRequest.Visible
                };

                await blogPostRepository.AddAsync(blogPost);

                var notification = new Notification
                {
                    Message = "Blog post created succesfully",
                    Type = Enums.NotificationType.Success
                };

                TempData["Notification"] = JsonSerializer.Serialize(notification);

                return RedirectToPage("/Admin/Blogs/List");
            }
            return Page();
        }
    }
}

BlogRazor.Web/Pages/Admin/Blogs/Edit.cshtml.cs
using BlogRazor.Web.Data;
using BlogRazor.Web.Enums;
using BlogRazor.Web.Models.Domain;
using BlogRazor.Web.Models.ViewModels;
using BlogRazor.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;

namespace BlogRazor.Web.Pages.Admin.Blogs
{

    [Authorize(Roles = "Admin")]
    public class EditModel : PageModel
    {
        private readonly IBlogPostRepository blogPostRepository;

        [BindProperty]
        public EditBlogPostRequest BlogPost { get; set; }


        public EditModel(IBlogPostRepository blogPostRepository)
        {
            this.blogPostRepository = blogPostRepository;
        }

        public async Task OnGet(Guid id)
        {
            var blogPostModel = await blogPostRepository.GetAsync(id);

            if (blogPostModel != null)
            {
                BlogPost = new EditBlogPostRequest
                {
                    Id = blogPostModel.Id,
                    Heading = blogPostModel.Heading,
                    PageTitle = blogPostModel.PageTitle,
                    Content = blogPostModel.Content,
                    ShortDescription = blogPostModel.ShortDescription,
                    Author = blogPostModel.Author,
                    Visible = blogPostModel.Visible,
                    PublishedDate = blogPostModel.PublishedDate
                };
            }
        }

        public async Task<IActionResult> OnPostEdit()
        {
            if (ModelState.IsValid)
            {
                try
                {

                    var blogPostModel = new BlogPost
                    {
                        Id = BlogPost.Id,
                        Heading = BlogPost.Heading,
                        PageTitle = BlogPost.PageTitle,
                        Content = BlogPost.Content,
                        ShortDescription = BlogPost.ShortDescription,
                        Author = BlogPost.Author,
                        Visible = BlogPost.Visible,
                        PublishedDate = BlogPost.PublishedDate
                    };

                    await blogPostRepository.UpdateAsync(blogPostModel);

                    var notification = new Notification
                    {
                        Message = "Blog post updated succesfully",
                        Type = Enums.NotificationType.Success
                    };

                    TempData["Notification"] = JsonSerializer.Serialize(notification);
                    return RedirectToPage("/Admin/Blogs/List");
                } catch (Exception ex)
                {
                    ViewData["Notification"] = new Notification
                    {
                        Message = "Something went wrong.",
                        Type = Enums.NotificationType.Error
                    };
                }
            }
            return Page();
        }

        public async Task<IActionResult> OnPostDelete()
        {

            var deleted = await blogPostRepository.DeleteAsync(BlogPost.Id);

            if (deleted)
            {
                var notification = new Notification
                {
                    Message = "Blog post deleted succesfully",
                    Type = Enums.NotificationType.Success
                };

                TempData["Notification"] = JsonSerializer.Serialize(notification);
                return RedirectToPage("/Admin/Blogs/List");
            }
            return Page();
        }
    }
}

BlogRazor.Web/Pages/Admin/Blogs/List.cshtml.cs
using BlogRazor.Web.Data;
using BlogRazor.Web.Models.Domain;
using BlogRazor.Web.Models.ViewModels;
using BlogRazor.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;

namespace BlogRazor.Web.Pages.Admin.Blogs
{

    [Authorize(Roles = "Admin")]
    public class ListModel : PageModel
    {

        private readonly IBlogPostRepository blogPostRepository;

        public List<BlogPost> BlogPosts { get; set; }

        public ListModel(IBlogPostRepository blogPostRepository)
        {
            this.blogPostRepository = blogPostRepository;
        }

        public async Task OnGet()
        {
            var notificationJson = (string)TempData["Notification"];

            if (notificationJson != null)
            {
                ViewData["Notification"] = JsonSerializer.Deserialize<Notification>(notificationJson);
            }

            BlogPosts = (await blogPostRepository.GetAllAsync())?.ToList();
        }
    }
}

BlogRazor.Web/Pages/Blog/Details.cshtml.cs
using BlogRazor.Web.Models.Domain;using BlogRazor.Web.Models.ViewModels;using BlogRazor.Web.Repositories;using Microsoft.AspNetCore.Identity;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.Mvc.RazorPages;using System.ComponentModel.DataAnnotations;namespace BlogRazor.Web.Pages.Blog
{    public class DetailsModel : PageModel
    {        private readonly IBlogPostRepository blogPostRepository;        private readonly IBlogPostLikeRepository blogPostLikeRepository;        private readonly IBlogPostCommentRepository blogPostCommentRepository;        private readonly SignInManager<IdentityUser> signInManager;        private readonly UserManager<IdentityUser> userManager;        public BlogPost BlogPost { get; set; }        public int TotalLikes { get; set; }        public bool Liked { get; set; }        [BindProperty]        public Guid BlogPostId { get; set; }        [BindProperty]        [Required]        [MinLength(1)]        [MaxLength(100)]        public string CommentDescription { get; set; }        public List<BlogComment> Comments { get; set; }        public DetailsModel(IBlogPostRepository blogPostRepository,IBlogPostLikeRepository blogPostLikeRepository,IBlogPostCommentRepository blogPostCommentRepository,            SignInManager<IdentityUser> signInManager,UserManager<IdentityUser> userManager)
        {            this.blogPostRepository = blogPostRepository;            this.blogPostLikeRepository = blogPostLikeRepository;            this.blogPostCommentRepository = blogPostCommentRepository;            this.signInManager = signInManager;            this.userManager = userManager;
        }        public async Task<IActionResult> OnGet(string heading)
        {
            await GetBlog(heading);            return Page();
        }        public async Task<IActionResult> OnPost(string heading)
        {            if (ModelState.IsValid)
            {
                if (signInManager.IsSignedIn(User) && !string.IsNullOrWhiteSpace(CommentDescription))
                {

                    var userId = userManager.GetUserId(User);

                    var comment = new BlogPostComment
                    {
                        BlogPostId = BlogPostId,
                        Description = CommentDescription,
                        DateAdded = DateTime.Now,
                        UserId = Guid.Parse(userId)
                    };

                    await blogPostCommentRepository.AddAsync(comment);
                }
                return RedirectToPage("/Blog/Details",new { heading = heading });
            }

            await GetBlog(heading);
            return Page();
        }        private async Task GetComments()
        {
            var blogPostComments = await blogPostCommentRepository.GetAllAsync(BlogPost.Id);
            var blogComments = new List<BlogComment>();

            foreach (var blogPostComment in blogPostComments)
            {
                blogComments.Add(new BlogComment
                {
                    DateAdded = blogPostComment.DateAdded,
                    Description = blogPostComment.Description,
                    Username = (await userManager.FindByIdAsync(blogPostComment.UserId.ToString())).UserName
                });
            }

            Comments = blogComments;
        }        private async Task GetBlog(string heading)
        {
            BlogPost = await blogPostRepository.GetAsync(heading);            if (BlogPost != null)
            {                BlogPostId = BlogPost.Id;                if (signInManager.IsSignedIn(User))
                {                    var likes = await blogPostLikeRepository.GetLikesForBlog(BlogPost.Id);                    var userId = userManager.GetUserId(User);                    Liked = likes.Any(x => x.UserId == Guid.Parse(userId));                    await GetComments();

                }                TotalLikes = await blogPostLikeRepository.GetTotalLikesForBlog(BlogPost.Id);
            }
        }
    }
}

BlogRazor.Web/Pages/Admin/Blogs/Add.cshtml
 @page
@model BlogRazor.Web.Pages.Admin.Blogs.AddModel
@{
}


<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>Add Blog Post</h1>
    </div>
</div>

<partial name="_Notification">

    <div>
        <div class="container">
            <form method="post">
                <div class="mb-3">
                    <label for="heading" class="form-label">Heading</label>
                    <input type="text" required class="form-control" id="heading" asp-for="AddBlogPostRequest.Heading">
                    <span class="text-danger" asp-validation-for="AddBlogPostRequest.Heading"></span>
                </div>

                <div class="mb-3">
                    <label for="PageTitle" class="form-label">Page Title</label>
                    <input type="text" required class="form-control" id="PageTitle" asp-for="AddBlogPostRequest.PageTitle">
                    <span class="text-danger" asp-validation-for="AddBlogPostRequest.PageTitle"></span>
                </div>

                <div class="mb-3">
                    <label for="content" class="form-label">Content</label>
                    <textarea class="form-control" required id="content" asp-for="AddBlogPostRequest.Content"></textarea>
                    <span class="text-danger" asp-validation-for="AddBlogPostRequest.Content"></span>
                </div>

                <div class="mb-3">
                    <label for="shortDescription" class="form-label">Short Description</label>
                    <input type="text" class="form-control" required id="shortDescription" asp-for="AddBlogPostRequest.ShortDescription">
                    <span class="text-danger" asp-validation-for="AddBlogPostRequest.ShortDescription"></span>
                </div>

                <div class="mb-3">
                    <label for="author" class="form-label">Author</label>
                    <input type="text" class="form-control" required id="author" asp-for="AddBlogPostRequest.Author">
                    <span class="text-danger" asp-validation-for="AddBlogPostRequest.Author"></span>
                </div>

                <div class="mb-3">
                    <label for="publishedDate" class="form-label">Published Date</label>
                    <input type="date" class="form-control" required id="publishedDate" asp-for="AddBlogPostRequest.PublishedDate">
                    <span class="text-danger" asp-validation-for="AddBlogPostRequest.PublishedDate"></span>
                </div>

                <div class="form-check mb-3">
                    <label class="form-check-label" for="isVisible">
                        <input class="form-check-input" type="checkbox" id="isVisible" asp-for="AddBlogPostRequest.Visible">
                        Is Visible
                    </label>
                </div>

                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>

    @section Scripts {
        <script>
            var editor = new FroalaEditor('#content');
        </script>
    }

BlogRazor.Web/Pages/Admin/Blogs/Edit.cshtml
@page "{id:Guid}"
@model BlogRazor.Web.Pages.Admin.Blogs.EditModel
@{
}

<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>Edit Blog Post</h1>
    </div>
</div>

<partial name="_Notification">

    @if (Model.BlogPost != null)
    {
        <div>
            <div class="container">
                <form method="post">
                    <div class="mb-3">
                        <label for="heading" class="form-label">Id</label>
                        <input type="text" class="form-control" id="id" asp-for="BlogPost.Id" readonly required>
                        <span class="text-danger" asp-validation-for="BlogPost.Id"></span>
                    </div>

                    <div class="mb-3">
                        <label for="heading" class="form-label">Heading</label>
                        <input type="text" class="form-control" id="heading" asp-for="BlogPost.Heading" required>
                        <span class="text-danger" asp-validation-for="BlogPost.Heading"></span>
                    </div>

                    <div class="mb-3">
                        <label for="PageTitle" class="form-label">Page Title</label>
                        <input type="text" class="form-control" id="PageTitle" asp-for="BlogPost.PageTitle" required>
                        <span class="text-danger" asp-validation-for="BlogPost.PageTitle"></span>
                    </div>

                    <div class="mb-3">
                        <label for="content" class="form-label">Content</label>
                        <textarea class="form-control" id="content" asp-for="BlogPost.Content" required></textarea>
                        <span class="text-danger" asp-validation-for="BlogPost.Content"></span>
                    </div>

                    <div class="mb-3">
                        <label for="shortDescription" class="form-label">Short Description</label>
                        <input type="text" class="form-control" id="shortDescription" asp-for="BlogPost.ShortDescription" required>
                        <span class="text-danger" asp-validation-for="BlogPost.ShortDescription"></span>
                    </div>

                    <div class="mb-3">
                        <label for="author" class="form-label">Author</label>
                        <input type="text" class="form-control" id="author" asp-for="BlogPost.Author" required>
                        <span class="text-danger" asp-validation-for="BlogPost.Author"></span>
                    </div>

                    <div class="mb-3">
                        <label for="publishedDate" class="form-label">Published Date</label>
                        <input type="date" class="form-control" id="publishedDate" asp-for="BlogPost.PublishedDate" required>
                        <span class="text-danger" asp-validation-for="BlogPost.PublishedDate"></span>
                    </div>

                    <div class="form-check mb-3">
                        <label class="form-check-label" for="isVisible">
                            <input class="form-check-input" type="checkbox" id="isVisible" asp-for="BlogPost.Visible">
                            Is Visible
                        </label>
                    </div>

                    <div class="mb-3 d-flex justify-content-between">
                        <button class="btn btn-primary" type="submit" asp-page-handler="Edit">Submit</button>
                        <button class="btn btn-danger" type="submit" asp-page-handler="Delete">Delete</button>
                    </div>
                </form>
            </div>
        </div>
    } else
    {
        <div class="container">
            <p>Blog Post not Found!</p>
        </div>
    }

    @section Scripts {
        <script>
            var editor = new FroalaEditor('#content');
        </script>
    }

BlogRazor.Web/Pages/Admin/Blogs/List.cshtml
@page
@model BlogRazor.Web.Pages.Admin.Blogs.ListModel
@{
}

<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>All Blog Posts</h1>
    </div>
</div>

<partial name="_Notification">


    @if (Model.BlogPosts != null && Model.BlogPosts.Any())
    {
        <div class="container">
            <table class="table">
                <thead>
                    <tr>
                        <td>Id</td>
                        <td>Heading</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var blogPost in Model.BlogPosts)
                    {
                        <tr>
                            <td>@blogPost.Id</td>
                            <td>@blogPost.Heading</td>
                            <td>
                                <a href="/Admin/Blogs/Edit/@blogPost.Id">View</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    } else
    {
        <div class="container">
            <p>No Blog posts were Found!</p>
        </div>
    }